In [1]:
import pandas
import numpy as np

In [8]:
force_field = pandas.read_csv(
    "ff_nucleus-compartment-level-undivided.csv"
)
force_field.index = force_field.columns

In [13]:
force_field.loc[:, ["SP", "NC", "LM"]]

          SP        NC        LM
A1 -0.530286  0.000000  0.000000
A2 -0.207641  0.000000  0.000000
B1  0.000000 -0.062946 -1.034611
B2  0.000000 -0.362142 -0.928730
B3  0.000000 -0.214521 -0.741693
B4  0.000000  0.000000  0.000000
NA  0.000000 -0.056540 -0.667915
NC  0.000000  0.000000  0.000000
SP  0.000000  0.000000  0.000000
LM  0.000000  0.000000  0.000000

In [14]:
force_field.loc[["SP", "NC", "LM"], :]

,A1,A2,B1,B2,B3,B4,NA,NC,SP,LM
SP,-0.530286,-0.207641,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
NC,0.000000,0.000000,-0.062946,-0.362142,-0.214521,0.0,-0.056540,0.0,0.0,0.0
LM,0.000000,0.000000,-1.034611,-0.928730,-0.741693,0.0,-0.667915,0.0,0.0,0.0

In [21]:
for divide_by in [3, 5, 8]:
    new_force_field = force_field.copy()
    new_force_field.loc[:, ["SP", "NC", "LM"]] /= divide_by
    new_force_field.loc[["SP", "NC", "LM"], :] /= divide_by

    new_force_field.to_csv(
        f"ff_nucleus-compartment-level_divided-by-{divide_by}.csv",
        index=False,
        float_format="%+.6f",
    )